import type { Character } from './types';

export const mockCharacters: Character[] = [
  {
    id: 'c1',
    name: '林晓',
    role: '主角',
    gender: '女',
    age: 17,
    description: '转学生，拥有能看到别人记忆的特殊能力。性格内向敏感，但内心善良温柔。因过去的某次事件而封闭了自己的内心，直到遇见陈雨泽才逐渐打开心扉。',
    personalityTraits: ['内向', '敏感', '善良', '温柔'],
    appearance: '黑色及肩长发，刘海微微遮住左眼。眼睛是清澈的琥珀色。身材纤细，常微微低着头。校服穿得整整齐齐，但总是显得有些孤单。',
    costume: '春野高中女生校服（白色衬衫+藏青色百褶裙+红色领结）。私服以浅色系连衣裙为主，喜欢戴一条银色星星项链。',
    background: '因为父母工作调动频繁转学，导致不擅长与人建立深厚关系。小时候曾遭遇一次意外，从此获得了看到他人记忆的能力。',
    specialSetting: '看到他人记忆的能力会在情绪激动时不受控制地触发。每次使用能力后会有短暂的头痛。',
    assets: [
      { id: 'a1', type: '立绘', name: '标准立绘', thumbnail: '/character-placeholder.jpg' },
      { id: 'a2', type: '表情', name: '微笑表情', thumbnail: '/character-placeholder.jpg' },
      { id: 'a3', type: '表情', name: '悲伤表情', thumbnail: '/character-placeholder.jpg' },
    ],
    hasGeneratedImage: true,
    avatarUrl: '/character-placeholder.jpg',
    relationships: [
      { targetCharacterId: 'c2', targetName: '陈雨泽', relation: '同桌/逐渐萌生的感情' },
      { targetCharacterId: 'c3', targetName: '苏瑶', relation: '室友/朋友' },
    ],
    scenes: ['教室初见', '天台对话', '樱花树下的约定'],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-20',
  },
  {
    id: 'c2',
    name: '陈雨泽',
    role: '主角',
    gender: '男',
    age: 17,
    description: '春野高中的校草，篮球队队长。外表阳光开朗，实则内心细腻。对林晓一见钟情，用耐心和温暖逐渐融化了她的心防。',
    personalityTraits: ['阳光', '开朗', '细腻', '勇敢'],
    appearance: '高挑身材，约180cm。棕色短发，笑起来有好看的酒窝。眼睛是深邃的墨绿色。总是挺直腰板，给人可靠的感觉。',
    costume: '春野高中男生校服（白色衬衫+藏青色长裤+红色领带）。篮球队服是7号。私服以休闲运动风为主。',
    background: '家境优渥但父母忙于工作，从小独立自主。初中时是篮球队的核心球员，因膝盖受伤休养过一段时间。',
    specialSetting: '对林晓的记忆能力隐约有所察觉，但选择尊重她的秘密。擅长烹饪，经常做便当给林晓。',
    assets: [
      { id: 'a4', type: '立绘', name: '标准立绘', thumbnail: '/character-placeholder.jpg' },
      { id: 'a5', type: '表情', name: '阳光笑容', thumbnail: '/character-placeholder.jpg' },
      { id: 'a6', type: '动作', name: '投篮姿势', thumbnail: '/character-placeholder.jpg' },
    ],
    hasGeneratedImage: true,
    avatarUrl: '/character-placeholder.jpg',
    relationships: [
      { targetCharacterId: 'c1', targetName: '林晓', relation: '同桌/深爱的人' },
      { targetCharacterId: 'c5', targetName: '赵子轩', relation: '发小/篮球队友' },
    ],
    scenes: ['教室初见', '篮球场比赛', '天台对话', '樱花树下的约定'],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-22',
  },
  {
    id: 'c3',
    name: '苏瑶',
    role: '配角',
    gender: '女',
    age: 17,
    description: '林晓的室友，活泼开朗的元气少女。是班级里的开心果，也是林晓在学校交到的第一个朋友。暗恋赵子轩却不敢表白。',
    personalityTraits: ['活泼', '开朗', '仗义', '迷糊'],
    appearance: '齐肩卷发，染了淡淡的栗子色。眼睛大大的很有神。总是面带笑容，喜欢戴各种可爱的发饰。',
    costume: '春野高中女生校服（裙子总是比规定短一点点）。私服是日系原宿风，色彩鲜艳。',
    background: '家中有一个弟弟，从小学会了照顾人。梦想是成为一名婚礼策划师。',
    specialSetting: '虽然看起来大大咧咧，其实很会察言观色。是林晓和陈雨泽的"爱情助攻"。',
    assets: [
      { id: 'a7', type: '立绘', name: '标准立绘', thumbnail: '/character-placeholder.jpg' },
      { id: 'a8', type: '表情', name: '元气笑容', thumbnail: '/character-placeholder.jpg' },
    ],
    hasGeneratedImage: true,
    avatarUrl: '/character-placeholder.jpg',
    relationships: [
      { targetCharacterId: 'c1', targetName: '林晓', relation: '室友/挚友' },
      { targetCharacterId: 'c5', targetName: '赵子轩', relation: '暗恋对象' },
    ],
    scenes: ['宿舍初见', '食堂吃饭', '助攻计划'],
    createdAt: '2024-01-16',
    updatedAt: '2024-03-18',
  },
  {
    id: 'c4',
    name: '沈婉清',
    role: '配角',
    gender: '女',
    age: 35,
    description: '春野高中的心理辅导老师，温柔知性。她是唯一知道林晓秘密的成年人，成为了林晓的精神支柱。',
    personalityTraits: ['温柔', '知性', '善解人意', '坚韧'],
    appearance: '黑色长发挽成优雅的发髻。戴着细框眼镜，眼神温和。身材匀称，穿着得体的职业装。',
    costume: '米白色针织衫搭配深色长裙。办公室常备一条温暖的羊毛披肩。',
    background: '曾是临床心理学医生，后转行成为学校心理老师。有过一段失败的婚姻，但始终保持对生活的热爱。',
    specialSetting: '办公室里永远有热茶和手工饼干。会弹奏古筝，有时会在放学后弹奏给学生听。',
    assets: [
      { id: 'a9', type: '立绘', name: '标准立绘', thumbnail: '/character-placeholder.jpg' },
    ],
    hasGeneratedImage: true,
    avatarUrl: '/character-placeholder.jpg',
    relationships: [
      { targetCharacterId: 'c1', targetName: '林晓', relation: '学生/被辅导者' },
    ],
    scenes: ['心理咨询室', '古筝演奏'],
    createdAt: '2024-01-20',
    updatedAt: '2024-02-28',
  },
  {
    id: 'c5',
    name: '赵子轩',
    role: '配角',
    gender: '男',
    age: 17,
    description: '陈雨泽的青梅竹马，篮球队的副队长。外表冷酷话少，实际上是个热心肠。对苏瑶有好感但不知道怎么表达。',
    personalityTraits: ['冷酷', '话少', '热心', '忠诚'],
    appearance: '黑色短发，略带自然卷。单眼皮，眼神锐利。身高182cm，体型修长结实。左耳有一颗银色耳钉。',
    costume: '春野高中男生校服（衬衫总是少扣一颗扣子）。篮球队服是11号。私服以黑色系街头风为主。',
    background: '父母离异，跟着奶奶长大。篮球是他唯一的宣泄出口，通过篮球奖学金进入春野高中。',
    specialSetting: '左耳的耳钉是奶奶送的护身符。擅长弹吉他，但只在最亲近的人面前演奏。',
    assets: [
      { id: 'a10', type: '立绘', name: '标准立绘', thumbnail: '/character-placeholder.jpg' },
      { id: 'a11', type: '服装', name: '篮球服', thumbnail: '/character-placeholder.jpg' },
    ],
    hasGeneratedImage: true,
    avatarUrl: '/character-placeholder.jpg',
    relationships: [
      { targetCharacterId: 'c2', targetName: '陈雨泽', relation: '发小/队友' },
      { targetCharacterId: 'c3', targetName: '苏瑶', relation: '暗恋对象' },
    ],
    scenes: ['篮球训练', '吉他独奏', '便利店偶遇'],
    createdAt: '2024-01-18',
    updatedAt: '2024-03-15',
  },
  {
    id: 'c6',
    name: '王美玲',
    role: '龙套',
    gender: '女',
    age: 17,
    description: '班里的学习委员，有点八卦但本质不坏。经常传播校园里的各种消息。',
    personalityTraits: ['八卦', '好胜', '热心'],
    appearance: '扎着双马尾，戴着圆框眼镜。总是背着书包里装满参考资料。',
    costume: '春野高中女生校服（总是佩戴学习委员袖章）。',
    background: '父母都是教师，从小在学业上被严格要求。',
    specialSetting: '消息灵通，班里大小事都知道。',
    assets: [],
    hasGeneratedImage: false,
    relationships: [],
    scenes: ['班级通知', '课间八卦'],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: 'c7',
    name: '张小明',
    role: '龙套',
    gender: '男',
    age: 17,
    description: '班里的搞笑担当，经常逗大家开心。陈雨泽的篮球队队友。',
    personalityTraits: ['搞笑', '乐观', '贪吃'],
    appearance: '微胖身材，圆圆的脸，总是笑眯眯的。头发有点自然卷。',
    costume: '春野高中男生校服（领带总是歪的）。',
    background: '家里开小吃店，从小对美食有研究。',
    specialSetting: '书包里永远有零食，人称"移动小卖部"。',
    assets: [],
    hasGeneratedImage: false,
    relationships: [
      { targetCharacterId: 'c2', targetName: '陈雨泽', relation: '队友' },
    ],
    scenes: ['课间搞笑', '篮球比赛'],
    createdAt: '2024-02-05',
    updatedAt: '2024-02-05',
  },
  {
    id: 'c8',
    name: '林母',
    role: '龙套',
    gender: '女',
    age: 42,
    description: '林晓的母亲，温柔但有些疏忽。因工作忙碌而缺少对女儿的陪伴。',
    personalityTraits: ['温柔', '忙碌', '内疚'],
    appearance: '和林晓相似的黑色长发，眼角有细纹。穿着朴素的职业装。',
    costume: '素色职业套装，偶尔系一条林晓送的丝巾。',
    background: '公司中层管理人员，常年出差。',
    specialSetting: '手机里存满了林晓的照片，却很少有机会一起看。',
    assets: [],
    hasGeneratedImage: false,
    relationships: [
      { targetCharacterId: 'c1', targetName: '林晓', relation: '母女' },
    ],
    scenes: ['家中对话', '机场送别'],
    createdAt: '2024-02-10',
    updatedAt: '2024-02-10',
  },
];

export const presetTraits = [
  '内向', '外向', '冷静', '冲动', '善良', '腹黑', '温柔', '强势',
  '乐观', '悲观', '敏感', '麻木', '聪明', '笨拙', '勇敢', '怯懦',
  '活泼', '冷酷', '细腻', '迷糊', '仗义', '忠诚', '开朗', '话少',
];

export const roleTypeOptions: { value: Character['role']; label: string }[] = [
  { value: '主角', label: '主角' },
  { value: '配角', label: '配角' },
  { value: '龙套', label: '龙套' },
];

export const genderOptions: { value: Character['gender']; label: string }[] = [
  { value: '男', label: '男' },
  { value: '女', label: '女' },
  { value: '其他', label: '其他' },
];
