import type { Shot } from './types';

export const mockShots: Shot[] = [
  {
    id: 's01',
    shotNumber: 1,
    shotType: '远景',
    duration: 5,
    status: '已完成',
    description: '樱花盛开的校园全景，春风拂过，花瓣如雪般飘落。阳光透过花枝洒在地面，形成斑驳的光影。远处的教学楼隐约可见，传来清脆的上课铃声。',
    cameraMovement: '固定',
    composition: '三分法',
    lighting: '自然光',
    characterAction: '无角色，纯场景展示',
    dialogue: '',
    sceneRef: '场景1：樱花校园·春',
    characters: [],
  },
  {
    id: 's02',
    shotNumber: 2,
    shotType: '全景',
    duration: 4,
    status: '已完成',
    description: '女主角林晓站在樱花树下，抬头仰望飘落的花瓣。她穿着淡蓝色校服，长发随风轻扬，手中握着一封泛黄的信笺。',
    cameraMovement: '推',
    composition: '中心构图',
    lighting: '侧光',
    characterAction: '林晓抬头望花瓣，手指轻抚信笺',
    dialogue: '',
    sceneRef: '场景1：樱花校园·春',
    characters: ['林晓'],
  },
  {
    id: 's03',
    shotNumber: 3,
    shotType: '中景',
    duration: 6,
    status: '已完成',
    description: '林晓缓缓拆开信笺，眼神从期待转为震惊。花瓣落在她的肩头和信纸上，她的手指微微颤抖。',
    cameraMovement: '跟',
    composition: '三分法',
    lighting: '柔光',
    characterAction: '林晓拆信，手指颤抖，眼神变化',
    dialogue: '（画外音）"一年后的今天，我会在樱花树下等你。"',
    sceneRef: '场景1：樱花校园·春',
    characters: ['林晓'],
  },
  {
    id: 's04',
    shotNumber: 4,
    shotType: '特写',
    duration: 3,
    status: '已完成',
    description: '信笺上的字迹特写——"给一年后的林晓"。一滴泪水落在信纸上，晕开了墨迹。',
    cameraMovement: '固定',
    composition: '中心构图',
    lighting: '顶光',
    characterAction: '泪水滴落',
    dialogue: '',
    sceneRef: '场景1：樱花校园·春',
    characters: ['林晓'],
  },
  {
    id: 's05',
    shotNumber: 5,
    shotType: '近景',
    duration: 5,
    status: '已完成',
    description: '林晓的眼中含泪，却露出微笑。她抬头看向樱花树，眼神中充满希望与坚定。',
    cameraMovement: '推',
    composition: '三分法',
    lighting: '逆光',
    characterAction: '林晓含泪微笑，眼神坚定',
    dialogue: '"我...我一定会去的。"',
    sceneRef: '场景1：樱花校园·春',
    characters: ['林晓'],
  },
  {
    id: 's06',
    shotNumber: 6,
    shotType: '全景',
    duration: 4,
    status: '已完成',
    description: '男主角陈默从教学楼方向跑来，在樱花树下四处张望。春风卷起他的衣角，花瓣在他周围飞舞。',
    cameraMovement: '移',
    composition: '对角线',
    lighting: '自然光',
    characterAction: '陈默奔跑，四处张望',
    dialogue: '"林晓——！"',
    sceneRef: '场景2：樱花树下·午后',
    characters: ['陈默'],
  },
  {
    id: 's07',
    shotNumber: 7,
    shotType: '中景',
    duration: 5,
    status: '生成中',
    description: '陈默停下脚步，发现树下的长椅上放着那封打开的信笺。他走近，弯腰拾起信纸，表情凝重。',
    cameraMovement: '跟',
    composition: '框架',
    lighting: '侧光',
    characterAction: '陈默拾起信笺，表情凝重',
    dialogue: '',
    sceneRef: '场景2：樱花树下·午后',
    characters: ['陈默'],
  },
  {
    id: 's08',
    shotNumber: 8,
    shotType: '近景',
    duration: 4,
    status: '等待中',
    description: '陈默紧握着信笺，望向远方。他的侧脸被夕阳镀上一层金色，眼神中带着复杂的情绪。',
    cameraMovement: '固定',
    composition: '三分法',
    lighting: '逆光',
    characterAction: '陈默握信，望向远方',
    dialogue: '"笨蛋，我等了你整整一年..."',
    sceneRef: '场景2：樱花树下·午后',
    characters: ['陈默'],
  },
  {
    id: 's09',
    shotNumber: 9,
    shotType: '远景',
    duration: 6,
    status: '等待中',
    description: '夕阳西下的校园全景，樱花树在金色余晖中如同燃烧的火焰。教学楼的轮廓被拉得很长，两个身影在树下遥遥相望。',
    cameraMovement: '拉',
    composition: '三分法',
    lighting: '自然光',
    characterAction: '两人遥遥相望',
    dialogue: '',
    sceneRef: '场景3：夕阳下的重逢',
    characters: ['林晓', '陈默'],
  },
  {
    id: 's10',
    shotNumber: 10,
    shotType: '特写',
    duration: 3,
    status: '失败',
    description: '两只手慢慢靠近的特写——林晓的手和陈默的手，指尖即将触碰。背景虚化为一片粉色的樱花海洋。',
    cameraMovement: '推',
    composition: '中心构图',
    lighting: '柔光',
    characterAction: '两人手指缓缓靠近',
    dialogue: '',
    sceneRef: '场景3：夕阳下的重逢',
    characters: ['林晓', '陈默'],
  },
  {
    id: 's11',
    shotNumber: 11,
    shotType: '中景',
    duration: 5,
    status: '草稿',
    description: '林晓和陈默并肩坐在长椅上，樱花花瓣如雨般落下。两人相视而笑，所有的误会和等待在这一刻化解。',
    cameraMovement: '固定',
    composition: '对称',
    lighting: '自然光',
    characterAction: '两人并肩而坐，相视而笑',
    dialogue: '"你来了。"\n"嗯，我来了。"',
    sceneRef: '场景3：夕阳下的重逢',
    characters: ['林晓', '陈默'],
  },
  {
    id: 's12',
    shotNumber: 12,
    shotType: '全景',
    duration: 6,
    status: '等待中',
    description: '樱花树下，两人相拥的画面。花瓣在夕阳中飞舞，画面渐渐淡出，化作一幅温暖的水彩画效果。字幕浮现"一年后，樱花依旧盛开"。',
    cameraMovement: '升',
    composition: '中心构图',
    lighting: '逆光',
    characterAction: '两人相拥，花瓣飞舞',
    dialogue: '"以后的每一年，我们都一起来看樱花吧。"',
    sceneRef: '场景3：夕阳下的重逢',
    characters: ['林晓', '陈默'],
  },
];

export const getTotalDuration = (shots: Shot[]): number =>
  shots.reduce((sum, s) => sum + s.duration, 0);

export const getStatusCount = (shots: Shot[], status: Shot['status']): number =>
  shots.filter((s) => s.status === status).length;
